// src/State/ActionTypes.js
export const FETCH_NUTRITION_REQUEST = 'FETCH_NUTRITION_REQUEST';
export const FETCH_NUTRITION_SUCCESS = 'FETCH_NUTRITION_SUCCESS';
export const FETCH_NUTRITION_FAILURE = 'FETCH_NUTRITION_FAILURE';
