// Action types for managing queries
export const GET_QUERIES_REQUEST = "GET_QUERIES_REQUEST";
export const GET_QUERIES_SUCCESS = "GET_QUERIES_SUCCESS";
export const GET_QUERIES_FAILURE = "GET_QUERIES_FAILURE";

export const GET_QUERY_BY_ID_REQUEST = "GET_QUERY_BY_ID_REQUEST";
export const GET_QUERY_BY_ID_SUCCESS = "GET_QUERY_BY_ID_SUCCESS";
export const GET_QUERY_BY_ID_FAILURE = "GET_QUERY_BY_ID_FAILURE";

export const CREATE_QUERY_REQUEST = "CREATE_QUERY_REQUEST";
export const CREATE_QUERY_SUCCESS = "CREATE_QUERY_SUCCESS";
export const CREATE_QUERY_FAILURE = "CREATE_QUERY_FAILURE";

export const ADD_REPLY_REQUEST = "ADD_REPLY_REQUEST";
export const ADD_REPLY_SUCCESS = "ADD_REPLY_SUCCESS";
export const ADD_REPLY_FAILURE = "ADD_REPLY_FAILURE";

export const GET_USER_QUERIES_REQUEST = 'GET_USER_QUERIES_REQUEST';
export const GET_USER_QUERIES_SUCCESS = 'GET_USER_QUERIES_SUCCESS';
export const GET_USER_QUERIES_FAILURE = 'GET_USER_QUERIES_FAILURE';

export const GET_NUTRITIONIST_QUERIES_REQUEST = 'GET_NUTRITIONIST_QUERIES_REQUEST';
export const GET_NUTRITIONIST_QUERIES_SUCCESS = 'GET_NUTRITIONIST_QUERIES_SUCCESS';
export const GET_NUTRITIONIST_QUERIES_FAILURE = 'GET_NUTRITIONIST_QUERIES_FAILURE';
