export const RESGISTER_REQUEST =" RESGISTER_REQUEST"
export const RESGISTER_SUCCESS =" RESGISTER_SUCCESS"
export const RESGISTER_FAILURE =" RESGISTER_FAILURE"

export const LOGIN_REQUEST =" LOGIN_REQUEST"
export const LOGIN_SUCCESS =" LOGIN_SUCCESS"
export const LOGIN_FAILURE =" LOGIN_FAILURE"

export const GET_USER_REQUEST =" GET_USER_REQUEST"
export const GET_USER_SUCCESS =" GET_USER_SUCCESS"
export const GET_USER_FAILURE =" GET_USER_FAILURE"

export const ADD_TO_FAVOURITE_REQUEST =" ADD_USER_FAVOURITE_REQUEST"
export const ADD_TO_FAVOURITE_SUCCESS =" ADD_USER_FAVOURITE_SUCCESS"
export const ADD_TO_FAVOURITE_FAILURE =" ADD_USER_FAVOURITE_FAILURE"

export const LOGOUT = "LOGOUT";