// Request Action Types
export const CREATE_REQUEST_REQUEST = "CREATE_REQUEST_REQUEST";
export const CREATE_REQUEST_SUCCESS = "CREATE_REQUEST_SUCCESS";
export const CREATE_REQUEST_FAILURE = "CREATE_REQUEST_FAILURE";

export const GET_REQUESTS_BY_NUTRITIONIST_REQUEST = "GET_REQUESTS_BY_NUTRITIONIST_REQUEST";
export const GET_REQUESTS_BY_NUTRITIONIST_SUCCESS = "GET_REQUESTS_BY_NUTRITIONIST_SUCCESS";
export const GET_REQUESTS_BY_NUTRITIONIST_FAILURE = "GET_REQUESTS_BY_NUTRITIONIST_FAILURE";

// ActionType.js

export const GET_REQUEST_BY_ID_REQUEST = 'GET_REQUEST_BY_ID_REQUEST';
export const GET_REQUEST_BY_ID_SUCCESS = 'GET_REQUEST_BY_ID_SUCCESS';
export const GET_REQUEST_BY_ID_FAILURE = 'GET_REQUEST_BY_ID_FAILURE';

export const UPDATE_REQUEST_WITH_PLAN_ID_REQUEST = 'UPDATE_REQUEST_WITH_PLAN_ID_REQUEST';
export const UPDATE_REQUEST_WITH_PLAN_ID_SUCCESS = 'UPDATE_REQUEST_WITH_PLAN_ID_SUCCESS';
export const UPDATE_REQUEST_WITH_PLAN_ID_FAILURE = 'UPDATE_REQUEST_WITH_PLAN_ID_FAILURE';

export const COMPLETE_REQUEST_BY_PLAN_ID_REQUEST = 'COMPLETE_REQUEST_BY_PLAN_ID_REQUEST';
export const COMPLETE_REQUEST_BY_PLAN_ID_SUCCESS = 'COMPLETE_REQUEST_BY_PLAN_ID_SUCCESS';
export const COMPLETE_REQUEST_BY_PLAN_ID_FAILURE = 'COMPLETE_REQUEST_BY_PLAN_ID_FAILURE';

export const GET_USER_REQUESTS_REQUEST = "GET_USER_REQUESTS_REQUEST";
export const GET_USER_REQUESTS_SUCCESS = "GET_USER_REQUESTS_SUCCESS";
export const GET_USER_REQUESTS_FAILURE = "GET_USER_REQUESTS_FAILURE";

export const UPDATE_REQUEST_STATUS_REQUEST = 'UPDATE_REQUEST_STATUS_REQUEST';
export const UPDATE_REQUEST_STATUS_SUCCESS = 'UPDATE_REQUEST_STATUS_SUCCESS';
export const UPDATE_REQUEST_STATUS_FAILURE = 'UPDATE_REQUEST_STATUS_FAILURE';

export const GET_REQUEST_BY_PLAN_ID_REQUEST = 'GET_REQUEST_BY_PLAN_ID_REQUEST';
export const GET_REQUEST_BY_PLAN_ID_SUCCESS = 'GET_REQUEST_BY_PLAN_ID_SUCCESS';
export const GET_REQUEST_BY_PLAN_ID_FAILURE = 'GET_REQUEST_BY_PLAN_ID_FAILURE';

export const UPDATE_ACHIEVED_WEIGHT_REQUEST = 'UPDATE_ACHIEVED_WEIGHT_REQUEST';
export const UPDATE_ACHIEVED_WEIGHT_SUCCESS = 'UPDATE_ACHIEVED_WEIGHT_SUCCESS';
export const UPDATE_ACHIEVED_WEIGHT_FAILURE = 'UPDATE_ACHIEVED_WEIGHT_FAILURE';

export const UPDATE_REQUEST_DESCRIPTION_AND_COMPLETE_REQUEST = 'UPDATE_REQUEST_DESCRIPTION_AND_COMPLETE_REQUEST';
export const UPDATE_REQUEST_DESCRIPTION_AND_COMPLETE_SUCCESS = 'UPDATE_REQUEST_DESCRIPTION_AND_COMPLETE_SUCCESS';
export const UPDATE_REQUEST_DESCRIPTION_AND_COMPLETE_FAILURE = 'UPDATE_REQUEST_DESCRIPTION_AND_COMPLETE_FAILURE';

export const UPDATE_REQUEST_COMMENT_REQUEST= 'UPDATE_REQUEST_COMMENT_REQUEST';
export const UPDATE_REQUEST_COMMENT_SUCCESS= 'UPDATE_REQUEST_COMMENT_SUCCESS';
export const UPDATE_REQUEST_COMMENT_FAILURE= 'UPDATE_REQUEST_COMMENT_FAILURE';

export const CREATE_OTHER_REQUEST_REQUEST = "CREATE_OTHER_REQUEST_REQUEST";
export const CREATE_OTHER_REQUEST_SUCCESS = "CREATE_OTHER_REQUEST_SUCCESS";
export const CREATE_OTHER_REQUEST_FAILURE = "CREATE_OTHER_REQUEST_FAILURE";


export const FINISH_REQUEST_BY_PLAN_ID_REQUEST = 'FINISH_REQUEST_BY_PLAN_ID_REQUEST';
export const FINISH_REQUEST_BY_PLAN_ID_SUCCESS = 'FINISH_REQUEST_BY_PLAN_ID_SUCCESS';
export const FINISH_REQUEST_BY_PLAN_ID_FAILURE = 'FINISH_REQUEST_BY_PLAN_ID_FAILURE';








