// Request Action Types
export const CREATE_REQUEST_REQUEST = "CREATE_REQUEST_REQUEST";
export const CREATE_REQUEST_SUCCESS = "CREATE_REQUEST_SUCCESS";
export const CREATE_REQUEST_FAILURE = "CREATE_REQUEST_FAILURE";

export const GET_REQUESTS_BY_NUTRITIONIST_REQUEST = "GET_REQUESTS_BY_NUTRITIONIST_REQUEST";
export const GET_REQUESTS_BY_NUTRITIONIST_SUCCESS = "GET_REQUESTS_BY_NUTRITIONIST_SUCCESS";
export const GET_REQUESTS_BY_NUTRITIONIST_FAILURE = "GET_REQUESTS_BY_NUTRITIONIST_FAILURE";

// ActionType.js

export const GET_REQUEST_BY_ID_REQUEST = 'GET_REQUEST_BY_ID_REQUEST';
export const GET_REQUEST_BY_ID_SUCCESS = 'GET_REQUEST_BY_ID_SUCCESS';
export const GET_REQUEST_BY_ID_FAILURE = 'GET_REQUEST_BY_ID_FAILURE';

export const UPDATE_REQUEST_WITH_PLAN_ID_REQUEST = 'UPDATE_REQUEST_WITH_PLAN_ID_REQUEST';
export const UPDATE_REQUEST_WITH_PLAN_ID_SUCCESS = 'UPDATE_REQUEST_WITH_PLAN_ID_SUCCESS';
export const UPDATE_REQUEST_WITH_PLAN_ID_FAILURE = 'UPDATE_REQUEST_WITH_PLAN_ID_FAILURE';

export const COMPLETE_REQUEST_BY_PLAN_ID_REQUEST = 'COMPLETE_REQUEST_BY_PLAN_ID_REQUEST';
export const COMPLETE_REQUEST_BY_PLAN_ID_SUCCESS = 'COMPLETE_REQUEST_BY_PLAN_ID_SUCCESS';
export const COMPLETE_REQUEST_BY_PLAN_ID_FAILURE = 'COMPLETE_REQUEST_BY_PLAN_ID_FAILURE';



