name: delivery
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  fl_chart: ^0.69.0
  http: ^1.2.1
  logger: ^2.4.0
  image_picker: ^1.1.2 # C
  path_provider: ^2.0.11
  path: ^1.8.0
  flutter_screenutil: ^5.9.3
  device_preview: ^1.0.0+2
  shared_preferences: ^2.0.8
  google_maps_flutter: ^2.7.0
  flutter_local_notifications: ^17.2.2
  web_socket_channel: ^3.0.1
  stomp_dart_client: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf


  assets:
    - assets/images/Background_image.png
    - assets/images/logo.jpg
    - assets/images/profile_picture.png
