export const CREATE_BMIPLAN_REQUEST = "CREATE_BMIPLAN_REQUEST";
export const CREATE_BMIPLAN_SUCCESS = "CREATE_BMIPLAN_SUCCESS";
export const CREATE_BMIPLAN_FAILURE = "CREATE_BMIPLAN_FAILURE";

export const ADD_MEAL_REQUEST = "ADD_MEAL_REQUEST";
export const ADD_MEAL_SUCCESS = "ADD_MEAL_SUCCESS";
export const ADD_MEAL_FAILURE = "ADD_MEAL_FAILURE";

// Action Types for Fetching Meals
export const FETCH_MEALS_REQUEST = "FETCH_MEALS_REQUEST";
export const FETCH_MEALS_SUCCESS = "FETCH_MEALS_SUCCESS";
export const FETCH_MEALS_FAILURE = "FETCH_MEALS_FAILURE";

export const FETCH_NUTRITION_REQUEST = 'FETCH_NUTRITION_REQUEST';
export const FETCH_NUTRITION_SUCCESS = 'FETCH_NUTRITION_SUCCESS';
export const FETCH_NUTRITION_FAILURE = 'FETCH_NUTRITION_FAILURE';

export const UPDATE_NUTRITION_REQUEST = 'UPDATE_NUTRITION_REQUEST';
export const UPDATE_NUTRITION_SUCCESS = 'UPDATE_NUTRITION_SUCCESS';
export const UPDATE_NUTRITION_FAILURE = 'UPDATE_NUTRITION_FAILURE';

export const GET_NUTRITION_REQUEST = 'GET_NUTRITION_REQUEST';
export const GET_NUTRITION_SUCCESS = 'GET_NUTRITION_SUCCESS';
export const GET_NUTRITION_FAILURE = 'GET_NUTRITION_FAILURE';