export const CREATE_MENU_REQUEST = "CREATE_MENU_REQUEST";
export const CREATE_MENU_SUCCESS = "CREATE_MENU_SUCCESS";
export const CREATE_MENU_FAILURE = "CREATE_MENU_FAILURE";

export const GET_ALL_MENUS_REQUEST = "GET_ALL_MENUS_REQUEST";
export const GET_ALL_MENUS_SUCCESS = "GET_ALL_MENUS_SUCCESS";
export const GET_ALL_MENUS_FAILURE = "GET_ALL_MENUS_FAILURE";

export const DELETE_MENU_REQUEST = "DELETE_MENU_REQUEST";
export const DELETE_MENU_SUCCESS = "DELETE_MENU_SUCCESS";
export const DELETE_MENU_FAILURE = "DELETE_MENU_FAILURE";

export const UPDATE_MENU_REQUEST = "UPDATE_MENU_REQUEST";
export const UPDATE_MENU_SUCCESS = "UPDATE_MENU_SUCCESS";
export const UPDATE_MENU_FAILURE = "UPDATE_MENU_FAILURE";

export const GET_MENU_BY_ID_REQUEST = "GET_MENU_BY_ID_REQUEST";
export const GET_MENU_BY_ID_SUCCESS = "GET_MENU_BY_ID_SUCCESS";
export const GET_MENU_BY_ID_FAILURE = "GET_MENU_BY_ID_FAILURE";

export const GET_MENUS_BY_RESTAURANT_ID_REQUEST = "GET_MENUS_BY_RESTAURANT_ID_REQUEST";
export const GET_MENUS_BY_RESTAURANT_ID_SUCCESS = "GET_MENUS_BY_RESTAURANT_ID_SUCCESS";
export const GET_MENUS_BY_RESTAURANT_ID_FAILURE = "GET_MENUS_BY_RESTAURANT_ID_FAILURE";
