export const START_PAYMENT_REQUEST = "START_PAYMENT_REQUEST";
export const START_PAYMENT_SUCCESS = "START_PAYMENT_SUCCESS";
export const START_PAYMENT_FAILURE = "START_PAYMENT_FAILURE";

export const HANDLE_NOTIFICATION_REQUEST = "HANDLE_NOTIFICATION_REQUEST";
export const HANDLE_NOTIFICATION_SUCCESS = "HANDLE_NOTIFICATION_SUCCESS";
export const HANDLE_NOTIFICATION_FAILURE = "HANDLE_NOTIFICATION_FAILURE";