// src/redux/actions/MealLogActionType.js

// Meal Log Action Types
export const CREATE_OR_UPDATE_MEALLOG_REQUEST = "CREATE_OR_UPDATE_MEALLOG_REQUEST";
export const CREATE_OR_UPDATE_MEALLOG_SUCCESS = "CREATE_OR_UPDATE_MEALLOG_SUCCESS";
export const CREATE_OR_UPDATE_MEALLOG_FAILURE = "CREATE_OR_UPDATE_MEALLOG_FAILURE";

export const ADD_MEAL_TO_LOG_REQUEST = "ADD_MEAL_TO_LOG_REQUEST";
export const ADD_MEAL_TO_LOG_SUCCESS = "ADD_MEAL_TO_LOG_SUCCESS";
export const ADD_MEAL_TO_LOG_FAILURE = "ADD_MEAL_TO_LOG_FAILURE";

export const GET_MEALS_BY_DATE_REQUEST = "GET_MEALS_BY_DATE_REQUEST";
export const GET_MEALS_BY_DATE_SUCCESS = "GET_MEALS_BY_DATE_SUCCESS";
export const GET_MEALS_BY_DATE_FAILURE = "GET_MEALS_BY_DATE_FAILURE";

export const UPDATE_NUTRITION_REQUEST = 'UPDATE_NUTRITION_REQUEST';
export const UPDATE_NUTRITION_SUCCESS = 'UPDATE_NUTRITION_SUCCESS';
export const UPDATE_NUTRITION_FAILURE = 'UPDATE_NUTRITION_FAILURE';

export const GET_NUTRITION_REQUEST = 'GET_NUTRITION_REQUEST';
export const GET_NUTRITION_SUCCESS = 'GET_NUTRITION_SUCCESS';
export const GET_NUTRITION_FAILURE = 'GET_NUTRITION_FAILURE';

export const GET_MEALLOG_STATUS_REQUEST = "GET_MEALLOG_STATUS_REQUEST";
export const GET_MEALLOG_STATUS_SUCCESS = "GET_MEALLOG_STATUS_SUCCESS";
export const GET_MEALLOG_STATUS_FAILURE = "GET_MEALLOG_STATUS_FAILURE";

