export const CREATE_NUTRITIONIST_REQUEST = "CREATE_NUTRITIONIST_REQUEST";
export const CREATE_NUTRITIONIST_SUCCESS = "CREATE_NUTRITIONIST_SUCCESS";
export const CREATE_NUTRITIONIST_FAILURE = "CREATE_NUTRITIONIST_FAILURE";

export const CHECK_NUTRITIONIST_REQUEST = "CHECK_NUTRITIONIST_REQUEST";
export const CHECK_NUTRITIONIST_REQUEST_SUCCESS = "CHECK_NUTRITIONIST_REQUEST_SUCCESS";
export const CHECK_NUTRITIONIST_REQUEST_FAILURE = "CHECK_NUTRITIONIST_REQUEST_FAILURE";

export const CHECK_NUTRITIONIST_REQUEST_CONFIRMED = "CHECK_NUTRITIONIST_REQUEST_CONFIRMED";
export const CHECK_NUTRITIONIST_REQUEST_CONFIRMED_SUCCESS = "CHECK_NUTRITIONIST_REQUEST_CONFIRMED_SUCCESS";
export const CHECK_NUTRITIONIST_REQUEST_CONFIRMED_FAILURE = "CHECK_NUTRITIONIST_REQUEST_CONFIRMED_FAILURE";
