export const CREATE_NUTRITIONIST_REQUEST = "CREATE_NUTRITIONIST_REQUEST";
export const CREATE_NUTRITIONIST_SUCCESS = "CREATE_NUTRITIONIST_SUCCESS";
export const CREATE_NUTRITIONIST_FAILURE = "CREATE_NUTRITIONIST_FAILURE";

export const CHECK_NUTRITIONIST_REQUEST = "CHECK_NUTRITIONIST_REQUEST";
export const CHECK_NUTRITIONIST_REQUEST_SUCCESS = "CHECK_NUTRITIONIST_REQUEST_SUCCESS";
export const CHECK_NUTRITIONIST_REQUEST_FAILURE = "CHECK_NUTRITIONIST_REQUEST_FAILURE";

export const CHECK_NUTRITIONIST_REQUEST_CONFIRMED = "CHECK_NUTRITIONIST_REQUEST_CONFIRMED";
export const CHECK_NUTRITIONIST_REQUEST_CONFIRMED_SUCCESS = "CHECK_NUTRITIONIST_REQUEST_CONFIRMED_SUCCESS";
export const CHECK_NUTRITIONIST_REQUEST_CONFIRMED_FAILURE = "CHECK_NUTRITIONIST_REQUEST_CONFIRMED_FAILURE";

export const GET_NUTRITIONIST_BY_ID_REQUEST = "GET_NUTRITIONIST_BY_ID_REQUEST";
export const GET_NUTRITIONIST_BY_ID_SUCCESS = "GET_NUTRITIONIST_BY_ID_SUCCESS";
export const GET_NUTRITIONIST_BY_ID_FAILURE = "GET_NUTRITIONIST_BY_ID_FAILURE";

export const GET_ALL_NUTRITIONISTS_REQUEST = "GET_ALL_NUTRITIONISTS_REQUEST";
export const GET_ALL_NUTRITIONISTS_SUCCESS = "GET_ALL_NUTRITIONISTS_SUCCESS";
export const GET_ALL_NUTRITIONISTS_FAILURE = "GET_ALL_NUTRITIONISTS_FAILURE";

// Fetch all nutritionist requests
export const GET_ALL_NUTRITIONIST_REQUESTS_REQUEST = "GET_ALL_NUTRITIONIST_REQUESTS_REQUEST";
export const GET_ALL_NUTRITIONIST_REQUESTS_SUCCESS = "GET_ALL_NUTRITIONIST_REQUESTS_SUCCESS";
export const GET_ALL_NUTRITIONIST_REQUESTS_FAILURE = "GET_ALL_NUTRITIONIST_REQUESTS_FAILURE";

// Fetch document by request ID
export const GET_DOCUMENT_REQUEST = "GET_DOCUMENT_REQUEST";
export const GET_DOCUMENT_SUCCESS = "GET_DOCUMENT_SUCCESS";
export const GET_DOCUMENT_FAILURE = "GET_DOCUMENT_FAILURE";

export const UPDATE_REQUEST_STATUS_REQUEST = "UPDATE_REQUEST_STATUS_REQUEST";
export const UPDATE_REQUEST_STATUS_SUCCESS = "UPDATE_REQUEST_STATUS_SUCCESS";
export const UPDATE_REQUEST_STATUS_FAILURE = "UPDATE_REQUEST_STATUS_FAILURE";



