export const CREATE_PLAN_REQUEST = "CREATE_PLAN_REQUEST";
export const CREATE_PLAN_SUCCESS = "CREATE_PLAN_SUCCESS";
export const CREATE_PLAN_FAILURE = "CREATE_PLAN_FAILURE";

export const GET_PLAN_DATA_REQUEST = "GET_PLAN_DATA_REQUEST";
export const GET_PLAN_DATA_SUCCESS = "GET_PLAN_DATA_SUCCESS";
export const GET_PLAN_DATA_FAILURE = "GET_PLAN_DATA_FAILURE";

export const UPDATE_MEAL_STATUS_REQUEST = "UPDATE_MEAL_STATUS_REQUEST";
export const UPDATE_MEAL_STATUS_SUCCESS = "UPDATE_MEAL_STATUS_SUCCESS";
export const UPDATE_MEAL_STATUS_FAILURE = "UPDATE_MEAL_STATUS_FAILURE";

export const GET_TOTAL_MEAL_COUNT_REQUEST = "GET_TOTAL_MEAL_COUNT_REQUEST";
export const GET_TOTAL_MEAL_COUNT_SUCCESS = "GET_TOTAL_MEAL_COUNT_SUCCESS";
export const GET_TOTAL_MEAL_COUNT_FAILURE = "GET_TOTAL_MEAL_COUNT_FAILURE";

export const GET_PLAN_BY_ID_REQUEST = "GET_PLAN_BY_ID_REQUEST";
export const GET_PLAN_BY_ID_SUCCESS = "GET_PLAN_BY_ID_SUCCESS";
export const GET_PLAN_BY_ID_FAILURE = "GET_PLAN_BY_ID_FAILURE";

export const COMPLETE_MEALPLAN_REQUEST = "COMPLETE_MEALPLAN_REQUEST";
export const COMPLETE_MEALPLAN_SUCCESS = "COMPLETE_MEALPLAN_SUCCESS";
export const COMPLETE_MEALPLAN_FAILURE = "COMPLETE_MEALPLAN_FAILURE";

export const UPDATE_MEAL_REQUEST = "UPDATE_MEAL_REQUEST";
export const UPDATE_MEAL_SUCCESS = "UPDATE_MEAL_SUCCESS";
export const UPDATE_MEAL_FAILURE = "UPDATE_MEAL_FAILURE";



export const UPDATE_MEAL_WEIGHT_REQUEST = "UPDATE_MEAL_WEIGHT_REQUEST";
export const UPDATE_MEAL_WEIGHT_SUCCESS = "UPDATE_MEAL_WEIGHT_SUCCESS";
export const UPDATE_MEAL_WEIGHT_FAILURE = "UPDATE_MEAL_WEIGHT_FAILURE";

// ActionType.js
export const GET_REQUESTS_BY_TOKEN_REQUEST = 'GET_REQUESTS_BY_TOKEN_REQUEST';
export const GET_REQUESTS_BY_TOKEN_SUCCESS = 'GET_REQUESTS_BY_TOKEN_SUCCESS';
export const GET_REQUESTS_BY_TOKEN_FAILURE = 'GET_REQUESTS_BY_TOKEN_FAILURE';




