// Plan Action Types
export const CREATE_PLAN_REQUEST = "CREATE_PLAN_REQUEST";
export const CREATE_PLAN_SUCCESS = "CREATE_PLAN_SUCCESS";
export const CREATE_PLAN_FAILURE = "CREATE_PLAN_FAILURE";

export const SET_BREAKFAST_REQUEST = "SET_BREAKFAST_REQUEST";
export const SET_BREAKFAST_SUCCESS = "SET_BREAKFAST_SUCCESS";
export const SET_BREAKFAST_FAILURE = "SET_BREAKFAST_FAILURE";

export const SET_LUNCH_REQUEST = "SET_LUNCH_REQUEST";
export const SET_LUNCH_SUCCESS = "SET_LUNCH_SUCCESS";
export const SET_LUNCH_FAILURE = "SET_LUNCH_FAILURE";

export const SET_DINNER_REQUEST = "SET_DINNER_REQUEST";
export const SET_DINNER_SUCCESS = "SET_DINNER_SUCCESS";
export const SET_DINNER_FAILURE = "SET_DINNER_FAILURE";

export const GET_PLAN_DATA_REQUEST = "GET_PLAN_DATA_REQUEST";
export const GET_PLAN_DATA_SUCCESS = "GET_PLAN_DATA_SUCCESS";
export const GET_PLAN_DATA_FAILURE = "GET_PLAN_DATA_FAILURE";

// Plan Status Action Types
export const UPDATE_PLAN_STATUS_REQUEST = "UPDATE_PLAN_STATUS_REQUEST";
export const UPDATE_PLAN_STATUS_SUCCESS = "UPDATE_PLAN_STATUS_SUCCESS";
export const UPDATE_PLAN_STATUS_FAILURE = "UPDATE_PLAN_STATUS_FAILURE";

export const UPDATE_MEAL_STATUS_REQUEST = "UPDATE_MEAL_STATUS_REQUEST";
export const UPDATE_MEAL_STATUS_SUCCESS = "UPDATE_MEAL_STATUS_SUCCESS";
export const UPDATE_MEAL_STATUS_FAILURE = "UPDATE_MEAL_STATUS_FAILURE";

export const GET_MEAL_STATUS_REQUEST = "GET_MEAL_STATUS_REQUEST";
export const GET_MEAL_STATUS_SUCCESS = "GET_MEAL_STATUS_SUCCESS";
export const GET_MEAL_STATUS_FAILURE = "GET_MEAL_STATUS_FAILURE";

export const COUNT_COMPLETED_MEALS_REQUEST = "COUNT_COMPLETED_MEALS_REQUEST";
export const COUNT_COMPLETED_MEALS_SUCCESS = "COUNT_COMPLETED_MEALS_SUCCESS";
export const COUNT_COMPLETED_MEALS_FAILURE = "COUNT_COMPLETED_MEALS_FAILURE";





