// src/State/complain/ActionType.js

export const ADD_COMPLAINT_REQUEST = "ADD_COMPLAINT_REQUEST";
export const ADD_COMPLAINT_SUCCESS = "ADD_COMPLAINT_SUCCESS";
export const ADD_COMPLAINT_FAILURE = "ADD_COMPLAINT_FAILURE";

export const FETCH_COMPLAINTS_REQUEST = "FETCH_COMPLAINTS_REQUEST";
export const FETCH_COMPLAINTS_SUCCESS = "FETCH_COMPLAINTS_SUCCESS";
export const FETCH_COMPLAINTS_FAILURE = "FETCH_COMPLAINTS_FAILURE";

export const DELETE_COMPLAINT_REQUEST = "DELETE_COMPLAINT_REQUEST";
export const DELETE_COMPLAINT_SUCCESS = "DELETE_COMPLAINT_SUCCESS";
export const DELETE_COMPLAINT_FAILURE = "DELETE_COMPLAINT_FAILURE";
