// Action Types for Complaints

// Fetch specific complaint
export const FIND_COMPLAINT_REQUEST = 'FIND_COMPLAINT_REQUEST';
export const FIND_COMPLAINT_SUCCESS = 'FIND_COMPLAINT_SUCCESS';
export const FIND_COMPLAINT_FAILURE = 'FIND_COMPLAINT_FAILURE';

// Clear all complaints
export const CLEAR_COMPLAINT_REQUEST = 'CLEAR_COMPLAINT_REQUEST';
export const CLEAR_COMPLAINT_SUCCESS = 'CLEAR_COMPLAINT_SUCCESS';
export const CLEAR_COMPLAINT_FAILURE = 'CLEAR_COMPLAINT_FAILURE';

// Get all complaints
export const GET_ALL_COMPLAINTS_REQUEST = 'GET_ALL_COMPLAINTS_REQUEST';
export const GET_ALL_COMPLAINTS_SUCCESS = 'GET_ALL_COMPLAINTS_SUCCESS';
export const GET_ALL_COMPLAINTS_FAILURE = 'GET_ALL_COMPLAINTS_FAILURE';

// Add a new complaint
export const ADD_COMPLAINT_REQUEST = 'ADD_COMPLAINT_REQUEST';
export const ADD_COMPLAINT_SUCCESS = 'ADD_COMPLAINT_SUCCESS';
export const ADD_COMPLAINT_FAILURE = 'ADD_COMPLAINT_FAILURE';

// Update an existing complaint
export const UPDATE_COMPLAINT_REQUEST = 'UPDATE_COMPLAINT_REQUEST';
export const UPDATE_COMPLAINT_SUCCESS = 'UPDATE_COMPLAINT_SUCCESS';
export const UPDATE_COMPLAINT_FAILURE = 'UPDATE_COMPLAINT_FAILURE';

// Remove a complaint
export const REMOVE_COMPLAINT_REQUEST = 'REMOVE_COMPLAINT_REQUEST';
export const REMOVE_COMPLAINT_SUCCESS = 'REMOVE_COMPLAINT_SUCCESS';
export const REMOVE_COMPLAINT_FAILURE = 'REMOVE_COMPLAINT_FAILURE';
